[[bond]]
source = "tpknam1qzvvqst747prcd77uh5t6g2jce58pcys6twrc66qr2ku00zdcj64q6fujm8"
validator = "tnam1q8azt2cpqmc6tr2gvg5v62e4jr0t9327yupaf595"
amount = "115"

[bond.signatures]
tpknam1qzvvqst747prcd77uh5t6g2jce58pcys6twrc66qr2ku00zdcj64q6fujm8 = "signam1qzp4jthc86rt5dqsgfxp9xzspacgcp7nlcu8mq93jvx789exurvuykv5yfcthah8f6q6uku6x2h2mywh8thyvfd7jmkv9zru0y378jqrf33u4k"
